name: face_attendance_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  tflite_flutter: ^0.10.0
  google_mlkit_face_detection: ^0.12.0
  image: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilefacenet.tflite
